server:
  port: 8080
  servlet:
    context-path: /shop-api

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC  # Note: typical MySQL port is 3306
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  access_key: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  refresh_key : "8u)=}s@pq9_o4&mv]1ezze&c}{!?]$hjt@xz&*((bc7{34&]n8@v?cunwetpwm?["

ghn:
  token: "fe055076-5488-11f0-ba75-a6ca4deb76d8"
  shop : "5862741"
  baseUrl : "https://online-gateway.ghn.vn/shiip/public-api"
#  valid-duration: 3600 # in second
#  refreshable-duration: 36000 # in seconds
cloud:
  link : "cloudinary://315416796683968:ihgzCqv84qAWXq_i8xZHXJbWJKQ@dazdwbzdw"